# Utiliser l'image officielle BIND de Docker Hub
FROM internetsystemsconsortium/bind9:latest

# Exposer le port 53 pour les requêtes DNS (UDP et TCP)
EXPOSE 53/udp
EXPOSE 53/tcp

# COPY named.conf /etc/bind/named.conf
# COPY db.example.com /etc/bind/db.example.com

# Démarrer le serveur BIND en mode premier plan (avec l'option -g pour afficher les logs)
CMD ["named", "-g"]
