# Utilisation de l'image officielle BIND
FROM internetsystemsconsortium/bind9:latest

# Exposer le port 53 pour les requêtes DNS
EXPOSE 53/udp
EXPOSE 53/tcp

# Ajouter la configuration BIND si nécessaire
# COPY named.conf /etc/bind/named.conf
# COPY db.example.com /etc/bind/db.example.com

# Démarrer le serveur BIND
CMD ["named", "-g"]
