# Utilisation de l'image Python
FROM python:3.9

# Définir le répertoire de travail
WORKDIR /app

# Copier les dépendances et installer
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copier l'application
COPY . .

# Exposer le port de l'application
EXPOSE 5000

# Lancer l'application
CMD ["python", "app.py"]
