---
- name: Configuration du serveur web dans Docker (Apache ou Nginx)
  hosts: localhost
  become: yes
  vars:
    server_choice: "{{ server_choice | default('Apache') }}"  # Valeur par défaut (Apache)
  tasks:
    - name: Vérifier si le conteneur existe déjà
      docker_container:
        name: web_server_container
        state: absent
      register: web_server_container_removed

    - name: Créer et démarrer le conteneur web
      docker_container:
        name: web_server_container
        image: "{{ 'httpd:latest' if server_choice == 'Apache' else 'nginx:latest' }}"
        state: started
        restart_policy: always
        exposed_ports:
          - "80"
        published_ports:
          - "80:80"
        networks:
          - default
      when: web_server_container_removed.changed
      register: web_server_status

    - name: Copier la configuration Apache si Apache est choisi
      copy:
        src: ./files/apache2.conf
        dest: /usr/local/apache2/conf/httpd.conf
      when: server_choice == 'Apache'

    - name: Copier la configuration Nginx si Nginx est choisi
      copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/nginx.conf
      when: server_choice == 'Nginx'

    - name: Vérifier si le serveur web fonctionne
      uri:
        url: "http://localhost:80"
        method: GET
        return_content: yes
      register: web_test

    - name: Afficher le résultat du test
      debug:
        msg: "Le serveur ${server_choice} est en fonctionnement et a répondu avec : {{ web_test.content }}"
      when: web_test is defined
